#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python -u preprocessing.py "$@"


# Don't forget to update experiment on final push
for exp in 01
do
  echo "Running Experiment $exp"
  python -u experiment${exp}.py "$@"
done

python -u manuscript_figures.py "$@"
