# hash:sha256:9f4876aee121c4c38977beed3b552a96a18ea54a5f3fa8ae2b255fe754ebeb72
FROM registry.codeocean.com/codeocean/pytorch:2.1.0-cuda11.8.0-mambaforge23.1.0-4-python3.10.12-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN pip3 install -U --no-cache-dir \
    matplotlib==3.10.6 \
    pandas==2.3.2
